version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    restart: always
    ports:
      - "${PORT:-4000}:${PORT:-4000}"
    volumes:
      - ./:/app
    env_file:
      - .env.development
    environment:
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - mining-mine-network
  db:
    image: postgres:16.2-alpine3.19
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=mining-mine-db
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - mining-mine-network
volumes:
  db-data:
networks:
  mining-mine-network:
    driver: bridge
