FROM golang:1.22.2-alpine3.19

WORKDIR /app

RUN apk add git mercurial

RUN git clone https://github.com/cosmtrek/air.git /tmp/air && \
  cd /tmp/air && \
  go install

COPY go.mod go.sum ./

RUN go mod download

# COPY . .

CMD ["air"]