name: self-hosted-db

on:
  workflow_dispatch:

jobs:
  pull_image:
    runs-on: ubuntu-latest

    environment: dev

    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}
    steps:
      - name: checkout branch
        uses: actions/checkout@v4
      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: run postgres container
        run: |
          docker run -d \
          --name db \
          -p ${DB_PORT}:5432 \
          -e POSTGRES_USER=${DB_USER} \
          -e POSTGRES_PASSWORD=${DB_PASSWORD} \
          -e POSTGRES_DB=${DB_NAME} \
          -v db-data:/var/lib/postgresql/data \
          --network mining-mine-network \
          postgres:16.2-alpine3.19
