name: self-hosted-db

on:
  workflow_dispatch:

jobs:
  pull_image:
    runs-on: ubuntu-latest

    environment: dev

    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}
    steps:
      - name: checkout branch
        uses: actions/checkout@v4
      - name: SSH into DigitalOcean Droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DIGITALOCEAN_DROPLET_IP}}
          username: ${{ secrets.DIGITALOCEAN_DROPLET_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_DROPLET_PASSWORD }}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
            docker run -d \
            --name db \
            -p ${{ secrets.DB_PORT }}:5432 \
            -e POSTGRES_USER=${{ secrets.DB_USER }} \
            -e POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e POSTGRES_DB=${{ secrets.DB_NAME }} \
            -v db-data:/var/lib/postgresql/data \
            --network mining-mine-network \
            postgres:16.2-alpine3.19
